name : CI-CD

on:
  push:
    branches: ["develop"]
jobs:
  build-and-deploy:
    runs-on: unbuntu-lastest

    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_USERNAME}}
      - name: build & push client
        run: |
          docker build -t peppa2k3/profile_website:1.0 ./client
          docker push peppa2k3/profile_website:1.0

      - name: Deploy to VPS 
        uses: appleboy/ssh-action@v1
          with:
            host: ${{secret.VPS_HOST}}
            username: ${{secret.VPS_USER}}
            key: ${{secret.VPS_KEY}}
            script: |
              cd /opt/profile
              docker compose pull
              docker compose up -d
              docker image prune -f
              
          
    
